export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Strony Premium',
    headline: 'Nowoczesne. Szybkie. Stabilne.',
    description: 'Nie zwlekaj z wyborem! Skontaktuj się ze mną już dziś, a w ciągu 24h odpiszę Ci co mogę dla Ciebie zrobić. Jestem pewny, że wspólnie wykonamy stronę twoich marzeń!',
    buttonLabel: 'Kontakt',
    imgStart: false,
    img: require('../../images/sv-1.svg'),
    alt: 'Page',
    darkText: false,
    dark: false,
    primary: true,
}